### ISSUE TITLE
pip install config2 still installs release 0.2.0

### ISSUE THREAD

**Issue by nerdicbynature** [grimen/python-config2#7]
Hi,

I still get release 0.2.0 if I run "pip install config2", which contains the bogus custom-environment-variables.yml handling. I need to install from Github directly to get version 0.2.1.

Also, get_env() still does not work.

However, very nice project! Perfectly fits my needs.

Best - André.

**Comment by grimen** [comment]
Thanks for the info, I just got back to fix reported issues - this weekend should be resolved.

**Comment by grimen** [comment]
Decided to attack the internally and externally reported issues today already. I didn't publish `v0.2.1` to PIP currently because critical bugs patched, so rather install `v0.3.0`+ because that one behaves well in all reported scenarios on Python 2 and 3. The library now has much more reliable config path detection based on call stack info.

I only have a what looks like smallish Travis CI test failure I noticed so will release `v0.3.1` tomorrow with green CI tests as well - though they all pass locally for Python 2 and 3 for me. =S 

https://travis-ci.com/grimen/python-config2/jobs/171056913

**Comment by nerdicbynature** [comment]
Confirmed: Installation now installs 0.3.0 by default, custom-environment-variables work like expected, file not need to exist and get() also reports configuration. Works like a charm. Thank a lot!

**Comment by grimen** [comment]
Awesome, thanks for the report.
